### PR TITLE
adding webcam support, adding nodes to tag robots, detect them, and t…

### PR DESCRIPTION
**Pull request by The-SS**
…rack them

### CODE REVIEW

**Comment by lakehanne** [comment]
Does 5.00pm work for you?

Sincerely,
Lekan

Demo or die.

**Comment by The-SS** [comment]
5 PM works for me.
We're still working on bug fixes.
I cannot promise to demo anything. At the time being, I'm still dealing
with many bugs in the code for formation control and inconsistencies
brought up by changes to the code that we're done yesterday.
So, I cannot promise you that I'll have a demo.

Sleiman

PS: my 2 week deadline is not over yet, at least not until next week.

**Comment by lakehanne** [comment]
Colon Capital D.

Sincerely,
Lekan

Demo or die.

**Comment by The-SS** [comment]
I see you changed your text color to red at the end.
Emphasis on how bloody this thing will be?

See you at 5PM.

Sleiman

**Pull request closed without merging**
